name: Update README with latest repositories

on:
  schedule:
    - cron: '0 */6 * * *'   # Run every 6 hours
  workflow_dispatch:        # Allow manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch latest repositories
        run: |
          echo "## 🚀 Latest Repositories" > latest_repos.md
          echo "" >> latest_repos.md
          curl -s "https://api.github.com/users/aniksutradhardev402/repos?sort=created&direction=desc" | \
          jq -r '.[] | "- [\(.name)](\(.html_url))"' | head -n 5 >> latest_repos.md

      - name: Update README.md
        run: |
          # Read the content of latest_repos.md and escape newlines and special characters for sed
          repos_content=$(cat latest_repos.md)
          repos_content_escaped=$(echo "$repos_content" | sed ':a;N;$!ba;s/\n/\\n/g')

          # Update README.md by replacing the section with the content
          sed -i "/<!--START_SECTION:repositories-->/, /<!--END_SECTION:repositories-->/c\<!--START_SECTION:repositories-->\n$repos_content_escaped\n<!--END_SECTION:repositories-->" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://$GH_TOKEN@github.com/aniksutradhardev402/aniksutradhardev402.git
          git add README.md
          git commit -m "Update latest repositories 🚀" || echo "No changes to commit"
          git push
        env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the token stored in GitHub secrets
