name: Update README with latest repositories

on:
  schedule:
    - cron: '0 */6 * * *'   # Run every 6 hours
  workflow_dispatch:        # Allow manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch latest repositories
        run: |
          echo "## 🚀 Latest Repositories" > latest_repos.md
          echo "" >> latest_repos.md
          curl -s "https://api.github.com/users/aniksutradhardev402/repos?sort=created&direction=desc" | \
          jq -r '.[] | "- [\(.name)](\(.html_url))"' | head -n 5 >> latest_repos.md

      - name: Update README.md
        run: |
          # Ensure that the content of the latest repositories file is read correctly with newline
          repos_content=$(cat latest_repos.md)
          # Use sed with newline properly in the replacement text
          sed -i "/<!--START_SECTION:repositories-->/, /<!--END_SECTION:repositories-->/c\<!--START_SECTION:repositories-->\n$repos_content\n<!--END_SECTION:repositories-->" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update latest repositories 🚀" || echo "No changes to commit"
          git push
